export class PokerList {
    public static readonly KEYS_NUMBER =  [
        21, 22, 23, 24, 31, 32, 33, 34, 41, 42, 43, 44, 51, 52, 53, 54, 61, 62, 63, 64, 71, 72,
        73, 74, 81, 82, 83, 84, 91, 92, 93, 94, 101, 102, 103, 104, 111, 112, 113, 114, 121, 122,
        123, 124, 131, 132, 133, 134, 141, 142, 143, 144
    ];
    public static readonly KEYS_STRING =  [
      '21', '22', '23', '24', '31', '32', '33', '34', '41', '42', '43', '44', '51', '52', '53', '54',
      '61', '62', '63', '64', '71', '72', '73', '74', '81', '82', '83', '84', '91', '92', '93', '94',
      '101', '102', '103', '104', '111', '112', '113', '114', '121', '122', '123', '124', '131', '132',
      '133', '134', '141', '142', '143', '144'
    ];
        public static readonly ALL_PORKER_JSON = {
            21: {
              NameCh: '梅花2',
              NameCh2: '梅花2',
              NameEn: 'Two of Club',
              NameCode: '2c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '2',
              PointEn: 'Two',
              PointCode: '2',
              PointCode2: '2'
            },
            22: {
              NameCh: '方塊2',
              NameCh2: '方塊2',
              NameEn: 'Two of Diamond',
              NameCode: '2d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '2',
              PointEn: 'Two',
              PointCode: '2',
              PointCode2: '2'
            },
            23: {
              NameCh: '紅心2',
              NameCh2: '紅心2',
              NameEn: 'Two of Heart',
              NameCode: '2h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '2',
              PointEn: 'Two',
              PointCode: '2',
              PointCode2: '2'
            },
            24: {
              NameCh: '黑桃2',
              NameCh2: '黑桃2',
              NameEn: 'Two of Spade',
              NameCode: '2s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '2',
              PointEn: 'Two',
              PointCode: '2',
              PointCode2: '2'
            },
            31: {
              NameCh: '梅花3',
              NameCh2: '梅花3',
              NameEn: 'Three of Club',
              NameCode: '3c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '3',
              PointEn: 'Three',
              PointCode: '3',
              PointCode2: '3'
            },
            32: {
              NameCh: '方塊3',
              NameCh2: '方塊3',
              NameEn: 'Three of Diamond',
              NameCode: '3d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '3',
              PointEn: 'Three',
              PointCode: '3',
              PointCode2: '3'
            },
            33: {
              NameCh: '紅心3',
              NameCh2: '紅心3',
              NameEn: 'Three of Heart',
              NameCode: '3h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '3',
              PointEn: 'Three',
              PointCode: '3',
              PointCode2: '3'
            },
            34: {
              NameCh: '黑桃3',
              NameCh2: '黑桃3',
              NameEn: 'Three of Spade',
              NameCode: '3s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '3',
              PointEn: 'Three',
              PointCode: '3',
              PointCode2: '3'
            },
            41: {
              NameCh: '梅花4',
              NameCh2: '梅花4',
              NameEn: 'Four of Club',
              NameCode: '4c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '4',
              PointEn: 'Four',
              PointCode: '4',
              PointCode2: '4'
            },
            42: {
              NameCh: '方塊4',
              NameCh2: '方塊4',
              NameEn: 'Four of Diamond',
              NameCode: '4d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '4',
              PointEn: 'Four',
              PointCode: '4',
              PointCode2: '4'
            },
            43: {
              NameCh: '紅心4',
              NameCh2: '紅心4',
              NameEn: 'Four of Heart',
              NameCode: '4h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '4',
              PointEn: 'Four',
              PointCode: '4',
              PointCode2: '4'
            },
            44: {
              NameCh: '黑桃4',
              NameCh2: '黑桃4',
              NameEn: 'Four of Spade',
              NameCode: '4s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '4',
              PointEn: 'Four',
              PointCode: '4',
              PointCode2: '4'
            },
            51: {
              NameCh: '梅花5',
              NameCh2: '梅花5',
              NameEn: 'Five of Club',
              NameCode: '5c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '5',
              PointEn: 'Five',
              PointCode: '5',
              PointCode2: '5'
            },
            52: {
              NameCh: '方塊5',
              NameCh2: '方塊5',
              NameEn: 'Five of Diamond',
              NameCode: '5d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '5',
              PointEn: 'Five',
              PointCode: '5',
              PointCode2: '5'
            },
            53: {
              NameCh: '紅心5',
              NameCh2: '紅心5',
              NameEn: 'Five of Heart',
              NameCode: '5h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '5',
              PointEn: 'Five',
              PointCode: '5',
              PointCode2: '5'
            },
            54: {
              NameCh: '黑桃5',
              NameCh2: '黑桃5',
              NameEn: 'Five of Spade',
              NameCode: '5s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '5',
              PointEn: 'Five',
              PointCode: '5',
              PointCode2: '5'
            },
            61: {
              NameCh: '梅花6',
              NameCh2: '梅花6',
              NameEn: 'Six of Club',
              NameCode: '6c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '6',
              PointEn: 'Six',
              PointCode: '6',
              PointCode2: '6'
            },
            62: {
              NameCh: '方塊6',
              NameCh2: '方塊6',
              NameEn: 'Six of Diamond',
              NameCode: '6d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '6',
              PointEn: 'Six',
              PointCode: '6',
              PointCode2: '6'
            },
            63: {
              NameCh: '紅心6',
              NameCh2: '紅心6',
              NameEn: 'Six of Heart',
              NameCode: '6h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '6',
              PointEn: 'Six',
              PointCode: '6',
              PointCode2: '6'
            },
            64: {
              NameCh: '黑桃6',
              NameCh2: '黑桃6',
              NameEn: 'Six of Spade',
              NameCode: '6s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '6',
              PointEn: 'Six',
              PointCode: '6',
              PointCode2: '6'
            },
            71: {
              NameCh: '梅花7',
              NameCh2: '梅花7',
              NameEn: 'Seven of Club',
              NameCode: '7c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '7',
              PointEn: 'Seven',
              PointCode: '7',
              PointCode2: '7'
            },
            72: {
              NameCh: '方塊7',
              NameCh2: '方塊7',
              NameEn: 'Seven of Diamond',
              NameCode: '7d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '7',
              PointEn: 'Seven',
              PointCode: '7',
              PointCode2: '7'
            },
            73: {
              NameCh: '紅心7',
              NameCh2: '紅心7',
              NameEn: 'Seven of Heart',
              NameCode: '7h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '7',
              PointEn: 'Seven',
              PointCode: '7',
              PointCode2: '7'
            },
            74: {
              NameCh: '黑桃7',
              NameCh2: '黑桃7',
              NameEn: 'Seven of Spade',
              NameCode: '7s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '7',
              PointEn: 'Seven',
              PointCode: '7',
              PointCode2: '7'
            },
            81: {
              NameCh: '梅花8',
              NameCh2: '梅花8',
              NameEn: 'Eight of Club',
              NameCode: '8c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '8',
              PointEn: 'Eight',
              PointCode: '8',
              PointCode2: '8'
            },
            82: {
              NameCh: '方塊8',
              NameCh2: '方塊8',
              NameEn: 'Eight of Diamond',
              NameCode: '8d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '8',
              PointEn: 'Eight',
              PointCode: '8',
              PointCode2: '8'
            },
            83: {
              NameCh: '紅心8',
              NameCh2: '紅心8',
              NameEn: 'Eight of Heart',
              NameCode: '8h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '8',
              PointEn: 'Eight',
              PointCode: '8',
              PointCode2: '8'
            },
            84: {
              NameCh: '黑桃8',
              NameCh2: '黑桃8',
              NameEn: 'Eight of Spade',
              NameCode: '8s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '8',
              PointEn: 'Eight',
              PointCode: '8',
              PointCode2: '8'
            },
            91: {
              NameCh: '梅花9',
              NameCh2: '梅花9',
              NameEn: 'Nine of Club',
              NameCode: '9c',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '9',
              PointEn: 'Nine',
              PointCode: '9',
              PointCode2: '9'
            },
            92: {
              NameCh: '方塊9',
              NameCh2: '方塊9',
              NameEn: 'Nine of Diamond',
              NameCode: '9d',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '9',
              PointEn: 'Nine',
              PointCode: '9',
              PointCode2: '9'
            },
            93: {
              NameCh: '紅心9',
              NameCh2: '紅心9',
              NameEn: 'Nine of Heart',
              NameCode: '9h',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '9',
              PointEn: 'Nine',
              PointCode: '9',
              PointCode2: '9'
            },
            94: {
              NameCh: '黑桃9',
              NameCh2: '黑桃9',
              NameEn: 'Nine of Spade',
              NameCode: '9s',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '9',
              PointEn: 'Nine',
              PointCode: '9',
              PointCode2: '9'
            },
            101: {
              NameCh: '梅花T',
              NameCh2: '梅花10',
              NameEn: 'Ten of Club',
              NameCode: 'Tc',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '10',
              PointEn: 'Ten',
              PointCode: 'T',
              PointCode2: '10'
            },
            102: {
              NameCh: '方塊T',
              NameCh2: '方塊10',
              NameEn: 'Ten of Diamond',
              NameCode: 'Td',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '10',
              PointEn: 'Ten',
              PointCode: 'T',
              PointCode2: '10'
            },
            103: {
              NameCh: '紅心T',
              NameCh2: '紅心10',
              NameEn: 'Ten of Heart',
              NameCode: 'Th',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '10',
              PointEn: 'Ten',
              PointCode: 'T',
              PointCode2: '10'
            },
            104: {
              NameCh: '黑桃T',
              NameCh2: '黑桃10',
              NameEn: 'Ten of Spade',
              NameCode: 'Ts',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '10',
              PointEn: 'Ten',
              PointCode: 'T',
              PointCode2: '10'
            },
            111: {
              NameCh: '梅花J',
              NameCh2: '梅花J',
              NameEn: 'Jack of Club',
              NameCode: 'Jc',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '11',
              PointEn: 'Jack',
              PointCode: 'J',
              PointCode2: 'J'
            },
            112: {
              NameCh: '方塊J',
              NameCh2: '方塊J',
              NameEn: 'Jack of Diamond',
              NameCode: 'Jd',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '11',
              PointEn: 'Jack',
              PointCode: 'J',
              PointCode2: 'J'
            },
            113: {
              NameCh: '紅心J',
              NameCh2: '紅心J',
              NameEn: 'Jack of Heart',
              NameCode: 'Jh',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '11',
              PointEn: 'Jack',
              PointCode: 'J',
              PointCode2: 'J'
            },
            114: {
              NameCh: '黑桃J',
              NameCh2: '黑桃J',
              NameEn: 'Jack of Spade',
              NameCode: 'Js',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '11',
              PointEn: 'Jack',
              PointCode: 'J',
              PointCode2: 'J'
            },
            121: {
              NameCh: '梅花Q',
              NameCh2: '梅花Q',
              NameEn: 'Queen of Club',
              NameCode: 'Qc',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '12',
              PointEn: 'Queen',
              PointCode: 'Q',
              PointCode2: 'Q'
            },
            122: {
              NameCh: '方塊Q',
              NameCh2: '方塊Q',
              NameEn: 'Queen of Diamond',
              NameCode: 'Qd',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '12',
              PointEn: 'Queen',
              PointCode: 'Q',
              PointCode2: 'Q'
            },
            123: {
              NameCh: '紅心Q',
              NameCh2: '紅心Q',
              NameEn: 'Queen of Heart',
              NameCode: 'Qh',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '12',
              PointEn: 'Queen',
              PointCode: 'Q',
              PointCode2: 'Q'
            },
            124: {
              NameCh: '黑桃Q',
              NameCh2: '黑桃Q',
              NameEn: 'Queen of Spade',
              NameCode: 'Qs',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '12',
              PointEn: 'Queen',
              PointCode: 'Q',
              PointCode2: 'Q'
            },
            131: {
              NameCh: '梅花K',
              NameCh2: '梅花K',
              NameEn: 'King of Club',
              NameCode: 'Kc',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '13',
              PointEn: 'King',
              PointCode: 'K',
              PointCode2: 'K'
            },
            132: {
              NameCh: '方塊K',
              NameCh2: '方塊K',
              NameEn: 'King of Diamond',
              NameCode: 'Kd',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '13',
              PointEn: 'King',
              PointCode: 'K',
              PointCode2: 'K'
            },
            133: {
              NameCh: '紅心K',
              NameCh2: '紅心K',
              NameEn: 'King of Heart',
              NameCode: 'Kh',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '13',
              PointEn: 'King',
              PointCode: 'K',
              PointCode2: 'K'
            },
            134: {
              NameCh: '黑桃K',
              NameCh2: '黑桃K',
              NameEn: 'King of Spade',
              NameCode: 'Ks',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              Point: '13',
              PointEn: 'King',
              PointCode: 'K',
              PointCode2: 'K'
            },
            141: {
              NameCh: '梅花A',
              NameCh2: '梅花A',
              NameEn: 'Ace of Club',
              NameCode: 'Ac',
              SuitCh: '梅花',
              SuitEn: 'Club',
              SuitCode: 'c',
              Point: '14',
              PointEn: 'Ace',
              PointCode: 'A',
              PointCode2: 'A'
            },
            142: {
              NameCh: '方塊A',
              NameCh2: '方塊A',
              NameEn: 'Ace of Diamond',
              NameCode: 'Ad',
              SuitCh: '方塊',
              SuitEn: 'Diamond',
              SuitCode: 'd',
              Point: '14',
              PointEn: 'Ace',
              PointCode: 'A',
              PointCode2: 'A'
            },
            143: {
              NameCh: '紅心A',
              NameCh2: '紅心A',
              NameEn: 'Ace of Heart',
              NameCode: 'Ah',
              SuitCh: '紅心',
              SuitEn: 'Heart',
              SuitCode: 'h',
              Point: '14',
              PointEn: 'Ace',
              PointCode: 'A',
              PointCode2: 'A'
            },
            144: {
              Point: '14',
              NameCh: '黑桃A',
              NameCh2: '黑桃A',
              NameEn: 'Ace of Spade',
              NameCode: 'As',
              SuitCh: '黑桃',
              SuitEn: 'Spade',
              SuitCode: 's',
              PointEn: 'Ace',
              PointCode: 'A',
              PointCode2: 'A'
            }
          };
}
